# Generated by Django 3.2.1 on 2021-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, upload_to='home/images')),
                ('hello_message', models.CharField(blank=True, max_length=255)),
                ('i_message', models.CharField(blank=True, max_length=255)),
                ('my_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
