# Generated by Django 3.2.1 on 2021-05-05 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_image', models.ImageField(blank=True, upload_to='about/images')),
                ('about_me', models.TextField(blank=True)),
                ('image_1', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_2', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_3', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_4', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_5', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_6', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_7', models.ImageField(blank=True, upload_to='about/photo_gallery')),
                ('image_8', models.ImageField(blank=True, upload_to='about/photo_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='contactinfo_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=255)),
                ('working_hour', models.CharField(max_length=255)),
                ('phone_nr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contacts_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('phone_nr', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='home_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
