# Generated by Django 3.2.1 on 2021-05-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0003_auto_20210505_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo_model',
            name='working_hour',
        ),
    ]
