# Generated by Django 3.2.1 on 2021-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0004_remove_contactinfo_model_working_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_head', models.CharField(blank=True, max_length=255)),
                ('post_image_one', models.ImageField(blank=True, upload_to='post/images')),
                ('post_text_one', models.TextField(blank=True)),
                ('post_image_two', models.ImageField(blank=True, upload_to='post/images')),
                ('post_text_two', models.TextField(blank=True)),
            ],
        ),
    ]
