# Generated by Django 3.2.1 on 2021-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0005_post_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
