# Generated by Django 3.2.1 on 2021-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0007_rename_post_detail_post_detail_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='related_fields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topics', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post_detail_model',
            name='related_topics',
            field=models.ManyToManyField(to='PersonalApp.related_fields'),
        ),
    ]
